apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: devopsified-app-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: devopsified-app
      useAnnotations: true
